# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eef1510b0d552f38ea2ff03910e87320f02f006d92cd370410fdc9d2cd7c2bb7b77aba04d1163869ab7a99b1ae85d5c4038ffade7c1c8e0c17572a31f2304b8

test:
  secret_key_base: 2111dda75aa76b9fc5dea2eb27cfdc770bfc7bee41c3ee5029e422125eabc1cb0a94ff0effa77084439cb74ce2ee47c52fc600c335597ec9d181356b8216ccd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
